language: python
python:
  - "3.6"
  - "3.7-dev"

# command to install dependencies
install:
  - pip install -r requirements-test.txt

# command to run tests
script:
  - pytest -v -m "not external_service"
